[package]
name = "pokedata_api_parsing"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
pokedata_api_entities = { path = "../entities" }
serde = { version = "1.0.210", features = ["derive"] }
