use crate::models::{bulk_response::*, message_response::MessageResponse, type_effectiveness::*};
use crate::resources;
use pokedata_api_entities::api::*;
use pokedata_api_entities::debug_stats::DebugStats;
use pokedata_api_entities::total_stats::TotalStats;
use pokemon_color::*;
use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(
        title = "PokeData API",
        description = "An API handling all kinds of pokemon data. Accumulated directly from the data sources of PokeAPI and PokemonTCG.io"
    ),
    paths(
        resources::ability::get_ability,
        resources::berry::get_berry,
        resources::berry_firmness::get_berry_firmness,
        resources::berry_flavor::get_berry_flavor,
        resources::color::get_color,
        resources::debug_stats::get_debug_stats,
        resources::egg_group::get_egg_group,
        resources::encounter::get_encounter,
        resources::encounter_condition::get_encounter_condition,
        resources::encounter_condition_value::get_encounter_condition_value,
        resources::encounter_method::get_encounter_method,
        resources::encounter_slot::get_encounter_slot,
        resources::evolution::get_evolution,
        resources::evolution_chain::get_evolution_chain,
        resources::evolution_trigger::get_evolution_trigger,
        resources::generation::get_generation,
        resources::growth_rate::get_growth_rate,
        resources::habitat::get_habitat,
        resources::item::get_item,
        resources::item_category::get_item_category,
        resources::item_flag::get_item_flag,
        resources::item_pocket::get_item_pocket,
        resources::language::get_language,
        resources::location::get_location,
        resources::location_area::get_location_area,
        resources::machine::get_machine,
        resources::ping::get_ping,
        resources::pokedex::get_pokedex,
        resources::pokemon::get_pokemon,
        resources::pokemon_move::get_move,
        resources::pokemon_move_ailment::get_move_ailment,
        resources::pokemon_move_category::get_move_category,
        resources::pokemon_move_damage_class::get_move_damage_class,
        resources::pokemon_move_effect::get_move_effect,
        resources::pokemon_move_flag::get_move_flag,
        resources::pokemon_move_target::get_move_target,
        resources::pokemon_type::get_pokemon_type,
        resources::region::get_region,
        resources::shape::get_shape,
        resources::stat::get_stat,
        resources::tcg_card::get_tcg_card,
        resources::tcg_set::get_tcg_set,
        resources::total_stats::get_total_stats,
        resources::pokemon_type_efficacy::get_type_efficacy,
        resources::pokemon_type_efficacy::get_type_efficacy_all,
        resources::species::get_species,
        resources::version::get_version,
        resources::version_group::get_version_group,
    ),
    tags(
        (name = "Misc", description = "Miscellaneous endpoints"),
        (name = "Abilities"),
        (name = "Berries"),
        (name = "Colors"),
        (name = "Egg Groups"),
        (name = "Encounters"),
        (name = "Evolutions"),
        (name = "Generations"),
        (name = "Growth Rates"),
        (name = "Habitats"),
        (name = "Items"),
        (name = "Languages"),
        (name = "Locations"),
        (name = "Machines"),
        (name = "Moves"),
        (name = "Pokemon"),
        (name = "TCG"),
        (name = "Types"),
        (name = "Versions"),
        (name = "Version Groups"),
    ),
    components(
        schemas(
            ability::Ability,
            ability_changelog_entry::AbilityChangelogEntry,
            berry::Berry,
            berry_firmness::BerryFirmness,
            berry_flavor::BerryFlavor,
            egg_group::EggGroup,
            encounter::Encounter,
            encounter_condition::EncounterCondition,
            encounter_condition_value::EncounterConditionValue,
            encounter_method::EncounterMethod,
            encounter_slot::EncounterSlot,
            evolution::Evolution,
            evolution_chain::EvolutionChain,
            evolution_chain::EvolutionChainNode,
            evolution_trigger::EvolutionTrigger,
            generation::Generation,
            growth_rate::GrowthRate,
            item::Item,
            item_category::ItemCategory,
            item_flag::ItemFlag,
            item_pocket::ItemPocket,
            language::Language,
            location::Location,
            location_area::LocationArea,
            localized_values::LocalizedValues,
            localized_values::VersionedLocalizedValues,
            localized_values::VersionGroupedLocalizedValues,
            machine::Machine,
            pokedex::Pokedex,
            pokemon::Pokemon,
            pokemon_move::PokemonMove,
            pokemon_move_ailment::PokemonMoveAilment,
            pokemon_move_category::PokemonMoveCategory,
            pokemon_move_changelog_entry::PokemonMoveChangelogEntry,
            pokemon_move_damage_class::PokemonMoveDamageClass,
            pokemon_move_effect::PokemonMoveEffect,
            pokemon_move_effect_changelog_entry::PokemonMoveEffectChangelogEntry,
            pokemon_move_flag::PokemonMoveFlag,
            pokemon_move_target::PokemonMoveTarget,
            PokemonColor,
            pokemon_habitat::PokemonHabitat,
            pokemon_shape::PokemonShape,
            pokemon_stats::PokemonStats,
            pokemon_type::PokemonType,
            pokemon_type_efficacy::PokemonTypeEfficacies,
            pokemon_type_efficacy::PokemonTypeEfficacyEntry,
            region::Region,
            species::Species,
            sprites::SpritePaths,
            stat::Stat,
            stat_value::StatValue,
            tcg_card::TcgCard,
            tcg_card::TcgCardAbility,
            tcg_card::TcgCardAncientTrait,
            tcg_card::TcgCardAttack,
            tcg_card::TcgCardImages,
            tcg_card::TcgCardResistance,
            tcg_card::TcgCardWeakness,
            tcg_legalities::TcgLegalities,
            tcg_set::TcgSet,
            tcg_set::TcgSetImages,
            type_slots::TypeSlots,
            type_slots::TypeSlotsPast,
            version::Version,
            version_group::VersionGroup,
            AllTypeEffectivenessResponse,
            AbilityBulkResponse,
            DebugStats,
            TotalStats,
            ColorBulkResponse,
            EggGroupBulkResponse,
            EncounterBulkResponse,
            EncounterConditionBulkResponse,
            EncounterConditionValueBulkResponse,
            EncounterMethodBulkResponse,
            EncounterSlotBulkResponse,
            EvolutionBulkResponse,
            EvolutionChainBulkResponse,
            EvolutionTriggerBulkResponse,
            GenerationBulkResponse,
            GrowthRateBulkResponse,
            HabitatBulkResponse,
            ItemBulkResponse,
            ItemCategoryBulkResponse,
            ItemFlagBulkResponse,
            ItemPocketBulkResponse,
            LanguageBulkResponse,
            LocationBulkResponse,
            LocationAreaBulkResponse,
            MachineBulkResponse,
            PokedexBulkResponse,
            PokemonBulkResponse,
            PokemonMoveBulkResponse,
            PokemonMoveAilmentBulkResponse,
            PokemonMoveCategoryBulkResponse,
            PokemonMoveDamageClassBulkResponse,
            PokemonMoveFlagBulkResponse,
            PokemonMoveTargetBulkResponse,
            PokemonTypeBulkResponse,
            RegionBulkResponse,
            ShapeBulkResponse,
            SpeciesBulkResponse,
            StatBulkResponse,
            TcgCardBulkResponse,
            VersionBulkResponse,
            VersionGroupBulkResponse,
            MessageResponse,
            TypeEffectivenessResponse,
        )
    )
)]
pub struct ApiDoc;